### ISSUE TITLE
Crash Alert low

### ISSUE THREAD

**Issue by MXASoundNDEv** [Yuri6037/TSCM_Starfall#2] opened 2019-02-23 17:44 UTC
[SF - ERROR] SF:lanai/processor/systems/ai_decoder.txt:137: attempt to call global 'CheckAutoMode' (a nil value)
[starfall_processor [2081]] Server Error
SF:lanai/processor/systems/ai_decoder.txt:137: attempt to call global 'CheckAutoMode' (a nil value)
stack traceback:
	SF:lanai/processor/systems/ai_decoder.txt:137: in function 'OnChatMessage'
	SF:lanai/processor/systems/ai_utils.txt:22: in function 'ReadData'
	SF:lanai/processor/systems/protocol.txt:85: in function <SF:lanai/processor/systems/protocol.txt:61>

**Comment by Yuri6037** [comment] 2019-02-26 16:34
Does this happen after the core is completely initialized (that means no more yellow ligh) or does this happen while the core is initializing ?

**Comment by Yuri6037** [comment] 2019-02-26 16:35
#3

**Comment by MXASoundNDEv** [comment] 2019-03-05 17:24
on initialiez is done completely

**Comment by Yuri6037** [comment] 2019-03-06 12:25
Ok then I'll have a look asap.

**Comment by Yuri6037** [comment] 2019-03-15 20:21
I checked it and I can't reproduce the crash when LanAI is completely initialized...
EDIT : Right the crash can be reproduced on any command when used before the core has fully initialized

**Comment by Yuri6037** [comment] 2019-03-15 20:38
Should be fixed now, comment if it's not...

**Comment by Yuri6037** [comment] 2019-03-15 20:39
#4

**Closed as completed by Yuri6037** 2019-03-15 20:38 UTC
