### ISSUE TITLE
create warp space            !ai yes

### ISSUE THREAD

**Issue by MXASoundNDEv** [Yuri6037/TSCM_Starfall#5] opened 2019-07-05 08:46 UTC
```LUA
[SF - ERROR] SF:lanai/libs/processor/lanaifiles.txt:47: attempt to concatenate local 'name' (a nil value)
[starfall_processor [1245]] Server Error
SF:lanai/libs/processor/lanaifiles.txt:47: attempt to concatenate local 'name' (a nil value)
stack traceback:
	SF:lanai/libs/processor/lanaifiles.txt:47: in function 'Overwrite'
	SF:lanai/processor/systems/points_manager.txt:100: in function 'OnAccepted'
	SF:lanai/processor/systems/ai_utils.txt:121: in function 'aiAcceptAction'
	SF:lanai/processor/ai_cmds/cmd_misc.txt:22: in function 'Func'
	SF:lanai/processor/systems/ai_decoder.txt:109: in function 'InterpretCommand'
	SF:lanai/processor/systems/ai_decoder.txt:155: in function 'OnChatMessage'
	SF:lanai/processor/systems/ai_utils.txt:22: in function 'ReadData'
	SF:lanai/processor/systems/protocol.txt:85: in function <SF:lanai/processor/systems/protocol.txt:61>

```

**Comment by Yuri6037** [comment] 2019-07-13 11:23
I'll check it as soon as possible.
Thanks for the report

**Comment by Yuri6037** [comment] 2019-07-13 11:37
All right sometimes I'm really dumb !! wrong variable name nice !!

EDIT : I'll try to do this today (Saturday), I just need some time to load GMod, make the changes and check the problem is fixed

**Comment by Yuri6037** [comment] 2019-07-13 11:55
Ok after some testing even with the correct variable names it fails with file limit reached sounds like a new limit has been introduced preventing the creation of files from LanAI

**Comment by Yuri6037** [comment] 2019-07-13 15:03
All right should be fixed.
Also I rewrote the part that saves config files on the OS to save on the file number limit...

Please close the issue if this updated solved the crash otherwise please respond here.

**Closed as completed** 2019-07-17 11:33 UTC
